#!/usr/bin/env python
"""Intergration testing for record_waypoints"""


import sys
import rospy
import unittest
import rostest
import arm_motion
from record_waypoints import MoveGroupPythonInterface as m


class TestRecordWaypoints(unittest.TestCase):
    def __init__(self, *args):
        """Init a test class for record_waypoints node
        """
        super(TestRecordWaypoints, self).__init__(*args)
        count = 0
        test = String('camera')
        

    
    def test_arm_action_callback(self, req):
        if req == test:
            self.assertEqual(count,1)

    


if __name__ == '__main__':
    rostest.rosrun('arm_motion','test_motion', TestRecordWaypoints, sys.argv)

