#!/usr/bin/env python
"""Intergration testing for record_waypoints"""


import sys
import rospy
import unittest
import rostest
from std_msgs.msg import String, Bool, Int16
import arm_motion
from arm_motion.record_waypoints import MoveGroupPythonInterface as m

class TestRecordWaypoints(unittest.TestCase):
    def __init__(self, *args):
        """Init a test class for record_waypoints node
        """
        super(TestRecordWaypoints, self).__init__(*args)
        self.count = 0
        self.test = String('camera')
        

    
    def test_arm_action_callback(self, req):
        if req == self.test:
            self.assertEqual(self.count,1)

    


if __name__ == '__main__':
    rostest.rosrun('arm_motion','test_motion', TestRecordWaypoints, sys.argv)

