#!/usr/bin/env python

import sys
import rospy
import unittest
import rostest
from camera_reconstruct.srv import save_pc
from sensor_msgs.msg import PointCloud2


class TestPC(unittest.TestCase):
    def __init__(self, *args):
        """
        Initialize a test class for pointcloud pipeline node
        """
        super(TestPC, self).__init__(*args)
        rospy.init_node('TestPC_node')
        rospy.wait_for_service('generate_pc/save_pc')
        self.pc = rospy.ServiceProxy('generate_pc/save_pc', save_pc)

    def test_pc(self):
        '''
        test to make sure service returns PointCloud2 message
        PointCloud2 message should be empty
        '''
        mypc = self.pc()
        frame = mypc.pc.header.frame_id
        height = mypc.pc.height
        self.assertEqual(frame,'')
        self.assertEqual(height,0)

    


if __name__ == '__main__':
    rostest.rosrun('camera_reconstruct','test_pointcloud', TestPC, sys.argv)

